### ISSUE TITLE
This does not autoload under composer

### ISSUE THREAD

**Issue by julesbl** [opencoconut/coconutphp#1]
Unfortunately this does not autoload under composer

$job = Coconut_Job::create($config);

Just comes back with cant find class Coconut_Job

Suggest putting the two classes in separate files and perhaps name space them

**Comment by rnicholls** [comment]
This seems to still be not fixed.

**Comment by BenBao93** [comment]
Yeah autoload with composer confirm does not work so far.

**Comment by mibstar** [comment]
I'm glad I've noticed this. Is this issue likely to be checked? Maybe a gentle nudge to @brunoceleste ? Thanks.

**Comment by brunoceleste** [comment]
Merged! Thanks guys
